insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Zondra', 'Droghan', 'Bakersfield', 'CA', '1 Shasta Park', 94710, 2652504699, 'fgdfasdf');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Armstrong', 'Tennant', 'Taft', 'CA', '3612 Mosinee Center', 93003, 9494386407, 'EXmmjbzc');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Modesta', 'Mizzen', 'Bakersfield', 'CA', '94 Continental Terrace', 94355, 1252016744,'ekNlyurD' );
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Bonita', 'Gregoli', 'Lamont', 'CA', '7204 Coleman Center', 93176, 1419642912, 'jOtmOyfc');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Caresse', 'Warlawe', 'Bakersfield', 'CA', '67807 Anhalt Center', 94477, 5323554738, 'DTnnRFtW');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Ailsun', 'Humber', 'Arvin', 'CA', '88301 Hoepker Plaza', 94181, 3964978483, 'gWWBtqJQ');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Cornall', 'Ivankin', 'Bakersfield', 'CA', '57 Grim Junction', 93010, 6942339583,'HVJkKbkA' );
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Tucker', 'Lye', 'Bakersfield', 'CA', '454 Columbus Alley', 93115, 6084885817, 'vDrxoGOM');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Cosimo', 'Hunstone', 'Bakersfield', 'CA', '4 Merry Road', 93435, 8272780272, 'GXKCoEIm');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Tatum', 'Harner', 'Bakersfield', 'CA', '13854 Reindahl Pass', 94225, 8471035074, 'OvFBIWPA');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Allyce', 'Mattedi', 'Bakersfield', 'CA', '42272 Kingsford Circle', 94194, 3013885170, 'ZbVbjQRl');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Tabbitha', 'MacDavitt', 'Taft', 'CA', '9737 Towne Junction', 93961, 7639513590, 'IqExUvxH');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Marylynne', 'Breazeall', 'Arvin', 'CA', '75 Bay Center', 94819, 7551063691,'vMDmZCCf' );
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Yanaton', 'Syversen', 'Arvin', 'CA', '1 Loomis Hill', 93458, 1907387693, 'nwVIsCOD');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Algernon', 'Dougharty', 'Bakersfield', 'CA', '4824 Straubel Point', 93351, 9409636386, 'vewMhsOE');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Val', 'Jagger', 'Lamont', 'CA', '6014 Lakewood Gardens Center', 93930, 1208418398, 'AZhmLJKb');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Valentina', 'Thurston', 'Bakersfield', 'CA', '955 Waubesa Court', 93795, 5557190947, 'vRPYmeNz');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Candice', 'Ligerton', 'Taft', 'CA', '723 Donald Plaza', 93143, 2576529192,'ZgQLsrPf' );
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Brandi', 'Heaps', 'Bakersfield', 'CA', '0410 Merrick Drive', 94625, 4729276804, 'SpCGGsFq');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Gladi', 'Berns', 'Lamont', 'CA', '42 Kedzie Point', 94375, 1203481641, 'orZTTeMq');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Konstanze', 'Dellar', 'Taft', 'CA', '0910 Dahle Road', 93017, 6632655734, 'bucDWYsA');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Briano', 'Tick', 'Lamont', 'CA', '41043 Jenna Avenue', 94123, 3717399732, 'fVBpaHas');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Celestine', 'MacKegg', 'Bakersfield', 'CA', '55 Grim Place', 93255, 8384272954,'NOVHUiNq' );
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Ilse', 'Benton', 'Lamont', 'CA', '77206 American Court', 94985, 4651195363, 'PtAmALjE');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Morry', 'Wedge', 'Wasco', 'CA', '4 Meadow Ridge Place', 93515, 2975012053, 'IRnJbnUj');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Rourke', 'Money', 'Bakersfield', 'CA', '07493 Sugar Hill', 93571, 8308710890, 'HwKFRfTY');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Jerome', 'Christley', 'Bakersfield', 'CA', '5 Shopko Place', 93164, 5246167379,'ImNDkOeG' );
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Alden', 'Fyrth', 'Arvin', 'CA', '9 Grayhawk Hill', 94259, 8087645551,'zCpRGsuU' );
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('Rayna', 'Tooze', 'Bakersfield', 'CA', '14 Bluestem Lane', 93309, 4698086703, 'NrLhSYxV');
insert into employee (fname, lname, city, state, street, zip, phone_number, password) values ('John', 'Doe', 'Lamont', 'CA', '7040 Fulton Pass', 94947, 1173026083, 'IQjKQzQG'); -- employee_john_doe